### ISSUE TITLE
您好，请问您是将sql中的数据映射到owl本体中，再用protege展示owl本体嘛？

### ISSUE THREAD

**Issue by mz2sj** [titangene/Automatic-Patent-Ontology-Construction-System#1]
如果我想直接在web端展示owl本体的数据该怎么操作呢？可否介绍下思路，谢谢！！！

**Comment by titangene** [comment]
如你 issue 標題所說，我的確是這樣展示本體的。
如果都是用 Java，web 就可用 Java Spring + Jena API 來處理，簡單一點可以使用 Apache Jena Fuseki
